hw3
OliverHDA/HomePetProject pull request #3
Opened 2021-08-08 21:32 UTC by OliverHDA

hw3

2021-08-10 06:50 UTC, PeterBukhal-Geekbrains requested changes
Есть критические замечания. Пока не принимаю.

2021-08-10 06:50 UTC, PeterBukhal-Geekbrains commented on app/src/main/java/ru/oliverhd/homepetproject/repository/GithubUsersRepo.kt
> +    fun getUsers(): Single<List<GithubUser>> {
:+1:

2021-08-10 06:50 UTC, PeterBukhal-Geekbrains commented on app/src/main/java/ru/oliverhd/homepetproject/user/UserPresenter.kt
> +        usersRepo
:-1: Ошибка не обработана. Будет фатал и приложение упадет.

2021-08-10 06:50 UTC, PeterBukhal-Geekbrains commented on app/src/main/java/ru/oliverhd/homepetproject/user/UserPresenter.kt
> +        usersRepo
:-1: Упущен важный момент про который мы говорили на вебинаре, это отмена цепочки в случае необходимости. В текущем виде этот момент не реализован, нужно использовать `Disposable` и отменить цепочку как минимум в методе презентера `onDestroy`.

2021-08-12 12:13 UTC, PeterBukhal-sovcombank approved these changes

2021-08-14 15:16 UTC, merged